-- SKLAD 1: HLAVNÍ KLUBOVNA (location_id = 1)
INSERT INTO equipment (name, category, total_quantity, location_id) VALUES
('Rodinný stan Husky Boston 5', 'Stany', 2, 1),
('Turistický stan Jurek Trio', 'Stany', 6, 1),
('Podpolohová celta pod stan (2x3m)', 'Stany', 10, 1),
('Zimní spací pytel Coleman', 'Stany', 5, 1),
('Samonafukovací karimatka Yate', 'Stany', 8, 1),
('Vojenská skládací polní postel', 'Stany', 4, 1),
('Moskytýra nad postel/celtu', 'Stany', 3, 1),
('Náhradní stanové tyčky (set)', 'Stany', 4, 1),
('Kolíky k týpí (dřevěné, velké)', 'Stany', 30, 1),
('Sada ocelových stanových kolíků', 'Stany', 5, 1),
('Velký táborový kotlík (20 litrů)', 'Vaření', 3, 1),
('Trojnožka nad oheň (skládací)', 'Vaření', 3, 1),
('Dvouplotýnkový plynový vařič Meva', 'Vaření', 2, 1),
('Plynová bomba (10 kg)', 'Vaření', 3, 1),
('Kuchařská naběračka (nerez)', 'Vaření', 4, 1),
('Skladový barel na vodu (50l)', 'Vaření', 4, 1),
('Pánev litinová na oheň (40cm)', 'Vaření', 2, 1),
('Táborový kuchyňský nůž', 'Vaření', 5, 1),
('Otvírák na konzervy (gastro)', 'Vaření', 3, 1),
('Termobox na přenášení jídla', 'Vaření', 2, 1),
('Kempingová sada nádobí (ešusy)', 'Vaření', 15, 1),
('Skládací dřez na nádobí', 'Vaření', 2, 1),
('Utěrky na nádobí (balení 20ks)', 'Vaření', 3, 1),
('Zdravotnický batoh (marodka)', 'Program', 2, 1),
('Sponzorský kufr s deskovkami', 'Program', 1, 1),
('Sada lakrosových palek (12 ks)', 'Program', 2, 1),
('Fotbalový míč Puma', 'Program', 4, 1),
('Volejbalový míč Molten', 'Program', 3, 1),
('Sada softbalových pálit a míčků', 'Program', 2, 1),
('Buzola Suunto', 'Program', 15, 1),
('Turistická mapa KČT', 'Program', 10, 1),
('Lanové bludiště (sada provázků)', 'Program', 2, 1),
('Výtvarný kufr (potřeby)', 'Program', 2, 1),
('Oddílová kronika', 'Program', 1, 1),
('Velká oddílová vlajka na stožár', 'Program', 2, 1),
('Dobíjecí čelovka Petzl', 'Ostatní', 12, 1),
('Lucerna Coleman na plyn', 'Ostatní', 4, 1),
('LED reflektor na stativu', 'Ostatní', 2, 1),
('Powerbanka Viking (20 000 mAh)', 'Ostatní', 5, 1),
('Přenosný repro JBL (na akce)', 'Ostatní', 1, 1),
('Vysílačka Baofeng (set 4 ks)', 'Ostatní', 2, 1),
('Megafon s sirénou', 'Ostatní', 2, 1),
('Skládací kempingový stůl', 'Ostatní', 4, 1),
('Kempingová židlička (rybářská)', 'Ostatní', 10, 1),
('Plastový úložný box s víkem 60l', 'Ostatní', 15, 1),
('Popisovač na bedny (černý)', 'Ostatní', 10, 1),
('Natahovací plachta s oky 4x6m', 'Ostatní', 6, 1),
('Sekundové lepidlo (balení 10ks)', 'Ostatní', 2, 1),
('Lepicí páska Duct Tape', 'Ostatní', 8, 1),
('Kanystr na benzín (5 litrů)', 'Ostatní', 3, 1);

-- SKLAD 2: GARÁŽ U VEDOUCÍHO (location_id = 2)
INSERT INTO equipment (name, category, total_quantity, location_id) VALUES
('Motorová pila Stihl', 'Nářadí', 1, 2),
('Sekera Fiskars X25 (velká)', 'Nářadí', 2, 2),
('Sekera Fiskars X10 (tesařská)', 'Nářadí', 4, 2),
('Ruční rámová pila na dřevo 70cm', 'Nářadí', 5, 2),
('Náhradní listy do rámové pily', 'Nářadí', 10, 2),
('Velké obouruční poříz na kůru', 'Nářadí', 2, 2),
('Lopata ocelová (s násadou)', 'Nářadí', 6, 2),
('Krumpáč tesařský (kovaný)', 'Nářadí', 3, 2),
('Rýč špičatý Fiskars', 'Nářadí', 4, 2),
('Kladivo tesařské (500g)', 'Nářadí', 6, 2),
('Palice bourací (3kg)', 'Nářadí', 2, 2),
('Sada plochých a kříž. šroubováků', 'Nářadí', 3, 2),
('Kombinované kleště', 'Nářadí', 5, 2),
('Aku vrtačka Makita', 'Nářadí', 2, 2),
('Kufr s hřebíky (mix, 5 kg)', 'Nářadí', 2, 2),
('Svinovací metr (50m, pásmo)', 'Nářadí', 2, 2),
('Vodováha hliníková (60cm)', 'Nářadí', 2, 2),
('Statické lano na stavby (50m)', 'Ostatní', 3, 2),
('Konopný provaz (klubko 100m)', 'Ostatní', 5, 2),
('Napínací popruh s ráčnou (kurt)', 'Ostatní', 8, 2),
('Horolezecká karabina šroubovací', 'Ostatní', 12, 2),
('Kladka jednoduchá (pro lanovky)', 'Ostatní', 4, 2),
('Horolezecký sedací úvazek', 'Ostatní', 4, 2),
('Pracovní rukavice kožené (pár)', 'Ostatní', 20, 2),
('Nafukovací kanoe Baraka', 'Ostatní', 3, 2),
('Vodácké pádlo Profiplast', 'Ostatní', 8, 2),
('Plovací vesta vodácká L', 'Ostatní', 6, 2),
('Plovací vesta dětská S', 'Ostatní', 6, 2),
('Házečka (záchranné lano 20m)', 'Ostatní', 3, 2),
('Vodotěsný barel na loď (50l)', 'Ostatní', 6, 2),
('Vodotěsný vak na záda 30l', 'Ostatní', 6, 2),
('Sada na opravu člunů (lepení)', 'Ostatní', 2, 2),
('Benzínová elektrocentrála Honda', 'Ostatní', 1, 2),
('Zahradní kolečko (stavební)', 'Nářadí', 2, 2),
('Velká mačeta na křoví', 'Nářadí', 2, 2),
('Ruční vrták do země (na kůly)', 'Nářadí', 1, 2),
('Lesnická křída na značení dřeva', 'Ostatní', 10, 2),
('Ocelové lanko na kuchyň (15m)', 'Ostatní', 2, 2),
('Skládací hliníkový žebřík', 'Nářadí', 1, 2),
('Krycí plachta na dřevo 6x10m', 'Ostatní', 4, 2),
('Prodlužovací kabel na bubnu 50m', 'Ostatní', 2, 2),
('Rozbočovač (pes, 3x zásuvka)', 'Ostatní', 4, 2),
('Outdoorová lopatka skládací', 'Nářadí', 5, 2),
('Velké nůžky na plech', 'Nářadí', 2, 2),
('Pilník na železo (plochý)', 'Nářadí', 3, 2),
('Brusný kámen (brousek)', 'Nářadí', 4, 2),
('Olej na mazání WD-40', 'Ostatní', 6, 2),
('Metla na zametání', 'Ostatní', 3, 2),
('Hasicí přístroj práškový (6 kg)', 'Ostatní', 2, 2),
('Velká autolékárnička (technická)', 'Ostatní', 1, 2);